### ISSUE TITLE
Expect to support scrollbar, scrollbar, and toggle of ugui

### ISSUE THREAD

**Issue by kane9527-e** [kyubuns/AkyuiUnity#35]
Expect to support scrollbar, scrollbar, and toggle of ugui

**Comment by kyubuns** [comment]
Scrollbar is added to Sample.
Toggle will have to wait a little longer.
https://github.com/kyubuns/AkyuiUnity/blob/main/SampleXd/Public%20Game%20UI.xd

**Comment by kane9527-e** [comment]
Thank you very much for your answer. If dropdown supports the above three basic ugui components, it is almost enough. Thank you again for your open source

**Comment by kane9527-e** [comment]
Thank you very much for your answer, scrollbar, dropdown, and scrollbar. If these three are supported, the basic ugui basic components are almost implemented. Thank you again for your open source

**Comment by kane9527-e** [comment]
Thank you very much for your answers, scrollbar, dropdown, and toggle. If these three are supported, the basic ugui basic components are almost implemented. Thank you again for your open source

**Comment by kyubuns** [comment]
New Toggle support!
https://github.com/kyubuns/AkyuiUnity/releases/tag/v1.3.5
<img width="752" alt="Screen Shot 2022-06-25 at 15 01 07" src="https://user-images.githubusercontent.com/961165/175760648-d410aaf5-f181-4078-8d13-2f43aa3049f2.png">

Dropdown may take some time, so we will move it to Discussions and support it once we have enough votes.
https://github.com/kyubuns/AkyuiUnity/discussions/36

**Comment by kane9527-e** [comment]
good job!Thank you very much
