### ISSUE TITLE
Parallel Import に対応していません

### ISSUE THREAD

**Issue by c3-hoge-fuga-piyo** [kyubuns/AkyuiUnity#43]
**Describe the bug**

Parallel Import が有効になっているとテクスチャが正しくインポートできず生成されたプレハブも不正な状態になってしまいました。

---

`Importer.ImportAsset` で `PostProcessImportAsset.ProcessingFile` などを設定し `AssetDatabase.ImportAsset` を通して `PostProcessImportAsset.OnPreprocessAsset` を呼び出していますが、 `Parallel Import` が有効になっている場合インポート処理が行われるのはワーカースレッド上になるため[ここ](https://github.com/kyubuns/AkyuiUnity/blob/7a2baa103bef62addc07f61323a1cfec7df9b513/Assets/AkyuiUnity/Editor/Importer.cs#L228-L243) の `using` スコープを抜けた（ `PostProcessImportAsset.ProcessingFile` などがリセットされた）後に `PostProcessImportAsset.OnPreprocessAsset` が呼ばれ[ここ](https://github.com/kyubuns/AkyuiUnity/blob/7a2baa103bef62addc07f61323a1cfec7df9b513/Assets/AkyuiUnity/Editor/Importer.cs#L274)でブロックされてしまい、結果テクスチャのインポート設定が意図していない状態になります（ `Sprite` になっていない、 `userData` が空など）

`ImportAssetOptions.ForceSynchronousImport` を指定して `AssetDatabase.ImportAsset` を行うように処理を変更してみましたが、手元の環境だとワーカースレッド上でインポート処理を行うことは変わらずで今回の問題への対応とはならず、 Parallel Import に対応するには時間がかかりそうだっため一旦 Issue という形で提起させていただきました。

**To Reproduce**
1. `Project Settings/Editor/Asset Pipeline/Parallel Import` を有効にする
    - 反映にUnity エディタの再起動が必要
2. 画像を含む適当な XD ファイルを `XdImportSettings` 経由でインポートする
3. アセットは生成されるが内容が正しくない
    - テクスチャがデフォルトのインポート設定のまま（ `Sprite` になっていない）ため、uGUIから参照できずにUIコンポーネントの `Source Image` などがすべて `None` になる
    - `PostProcessImportAsset.OnPreprocessAsset` がスキップされるため、 `userData` にJSONデータが入らず[ここ](https://github.com/kyubuns/AkyuiUnity/blob/7a2baa103bef62addc07f61323a1cfec7df9b513/Assets/AkyuiUnity/Editor/Importer.cs#L173-L181) で例外が発生する

※非同期処理による問題なので環境によらず再現できるか不明です…… :bow: 

**Expected behavior**

Parallel Import が有効になっていてもアセットが正しい状態で生成される。

**Environment**

- Windows 10
- Unity 2022.2.0f1
- 7a2baa103bef62addc07f61323a1cfec7df9b513

※Parallel Import 自体は Unity 2021.2 から提供されているため、おそらくこれ以降のバージョンなら発生する可能性があります。

**Comment by kyubuns** [comment]
報告ありがとうございます。
[v1.4.0](https://github.com/kyubuns/AkyuiUnity/releases/tag/v1.4.0)にて対応を行いました。
