### ISSUE TITLE
improt XD Error:

### ISSUE THREAD

**Issue by kane9527-e** [kyubuns/AkyuiUnity#44]
branches:main
NullReferenceException: Object reference not set to an instance of an object
Unity.VectorGraphics.Editor.SVGImporter.BuildTexture (UnityEngine.Sprite sprite, System.String name) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:552)
Unity.VectorGraphics.Editor.SVGImporter.GenerateTexturedSpriteAsset (UnityEditor.AssetImporters.AssetImportContext ctx, UnityEngine.Sprite sprite, System.String name) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:452)
Unity.VectorGraphics.Editor.SVGImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:336)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <11d97693183d4a6bb35c29ae7882c66b>:0)
UnityEditor.AssetDatabase:ImportAsset(String)
AkyuiUnity.Xd.SvgToPng:Convert(String, Vector2, ViewportOptions, XdImportSettings) (at Assets/AkyuiUnity.Xd/Editor/Svg/SvgToPng.cs:52)
AkyuiUnity.Xd.<>c__DisplayClass5_2:<RenderImage>b__0() (at Assets/AkyuiUnity.Xd/Editor/XdObjectParser/ShapeObjectParser.cs:126)
AkyuiUnity.Xd.XdAssetHolder:Load(String) (at Assets/AkyuiUnity.Xd/Editor/XdAssetHolder.cs:41)
AkyuiUnity.Xd.XdAkyuiLoader:LoadAsset(String) (at Assets/AkyuiUnity.Xd/Editor/XdAkyuiLoader.cs:69)
AkyuiUnity.Editor.Importer:ImportAssets(IAkyuiImportSettings, IAkyuiLoader, PathGetter, AkyuiLogger, IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:191)
AkyuiUnity.Editor.Importer:Import(IAkyuiImportSettings, IAkyuiLoader, AkyuiLogger, IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:87)
AkyuiUnity.Editor.Importer:Import(IAkyuiImportSettings, IAkyuiLoader[]) (at Assets/AkyuiUnity/Editor/Importer.cs:46)
AkyuiUnity.Xd.XdImporter:Import(XdImportSettings, String[]) (at Assets/AkyuiUnity.Xd/Editor/XdImporter.cs:45)
AkyuiUnity.Xd.XdImportSettingsEditor:OnInspectorGUI() (at Assets/AkyuiUnity.Xd/Editor/XdImportSettingsEditor.cs:38)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by kane9527-e** [comment]
Asset import failed, "Assets/Temp.svg" > NullReferenceException: Object reference not set to an instance of an object
Unity.VectorGraphics.Editor.SVGImporter.BuildTexture (UnityEngine.Sprite sprite, System.String name) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:552)
Unity.VectorGraphics.Editor.SVGImporter.GenerateTexturedSpriteAsset (UnityEditor.AssetImporters.AssetImportContext ctx, UnityEngine.Sprite sprite, System.String name) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:452)
Unity.VectorGraphics.Editor.SVGImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.20/Editor/SVGImporter.cs:336)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <11d97693183d4a6bb35c29ae7882c66b>:0)
UnityEditor.AssetDatabase:ImportAsset(String)
AkyuiUnity.Xd.SvgToPng:Convert(String, Vector2, ViewportOptions, XdImportSettings) (at Assets/AkyuiUnity.Xd/Editor/Svg/SvgToPng.cs:52)
AkyuiUnity.Xd.<>c__DisplayClass5_2:<RenderImage>b__0() (at Assets/AkyuiUnity.Xd/Editor/XdObjectParser/ShapeObjectParser.cs:126)
AkyuiUnity.Xd.XdAssetHolder:Load(String) (at Assets/AkyuiUnity.Xd/Editor/XdAssetHolder.cs:41)
AkyuiUnity.Xd.XdAkyuiLoader:LoadAsset(String) (at Assets/AkyuiUnity.Xd/Editor/XdAkyuiLoader.cs:69)
AkyuiUnity.Editor.Importer:ImportAssets(IAkyuiImportSettings, IAkyuiLoader, PathGetter, AkyuiLogger, IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:191)
AkyuiUnity.Editor.Importer:Import(IAkyuiImportSettings, IAkyuiLoader, AkyuiLogger, IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:87)
AkyuiUnity.Editor.Importer:Import(IAkyuiImportSettings, IAkyuiLoader[]) (at Assets/AkyuiUnity/Editor/Importer.cs:46)
AkyuiUnity.Xd.XdImporter:Import(XdImportSettings, String[]) (at Assets/AkyuiUnity.Xd/Editor/XdImporter.cs:45)
AkyuiUnity.Xd.XdImportSettingsEditor:OnInspectorGUI() (at Assets/AkyuiUnity.Xd/Editor/XdImportSettingsEditor.cs:38)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

UnityEditor.AssetDatabase:ImportAsset (string)
AkyuiUnity.Xd.SvgToPng:Convert (string,UnityEngine.Vector2,Unity.VectorGraphics.ViewportOptions,AkyuiUnity.Xd.XdImportSettings) (at Assets/AkyuiUnity.Xd/Editor/Svg/SvgToPng.cs:52)
AkyuiUnity.Xd.ShapeObjectParser/<>c__DisplayClass5_2:<RenderImage>b__0 () (at Assets/AkyuiUnity.Xd/Editor/XdObjectParser/ShapeObjectParser.cs:126)
AkyuiUnity.Xd.XdAssetHolder:Load (string) (at Assets/AkyuiUnity.Xd/Editor/XdAssetHolder.cs:41)
AkyuiUnity.Xd.XdAkyuiLoader:LoadAsset (string) (at Assets/AkyuiUnity.Xd/Editor/XdAkyuiLoader.cs:69)
AkyuiUnity.Editor.Importer:ImportAssets (AkyuiUnity.Editor.ScriptableObject.IAkyuiImportSettings,AkyuiUnity.Loader.IAkyuiLoader,AkyuiUnity.Editor.PathGetter,AkyuiUnity.Editor.AkyuiLogger,AkyuiUnity.Editor.IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:191)
AkyuiUnity.Editor.Importer:Import (AkyuiUnity.Editor.ScriptableObject.IAkyuiImportSettings,AkyuiUnity.Loader.IAkyuiLoader,AkyuiUnity.Editor.AkyuiLogger,AkyuiUnity.Editor.IAkyuiProgress) (at Assets/AkyuiUnity/Editor/Importer.cs:87)
AkyuiUnity.Editor.Importer:Import (AkyuiUnity.Editor.ScriptableObject.IAkyuiImportSettings,AkyuiUnity.Loader.IAkyuiLoader[]) (at Assets/AkyuiUnity/Editor/Importer.cs:46)
AkyuiUnity.Xd.XdImporter:Import (AkyuiUnity.Xd.XdImportSettings,string[]) (at Assets/AkyuiUnity.Xd/Editor/XdImporter.cs:45)
AkyuiUnity.Xd.XdImportSettingsEditor:OnInspectorGUI () (at Assets/AkyuiUnity.Xd/Editor/XdImportSettingsEditor.cs:38)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by kane9527-e** [comment]
NullReferenceException: Object reference not set to an instance of an object
AkyuiUnity.Loader.AkyuiCompressor.Compress (AkyuiUnity.Loader.IAkyuiLoader loader) (at Assets/AkyuiUnity/Loader/AkyuiCompressor.cs:47)
AkyuiUnity.Xd.XdImporter.ExportAkyui (AkyuiUnity.Xd.XdImportSettings xdSettings, System.Collections.Generic.List`1[T] loaders, AkyuiUnity.Editor.AkyuiLogger logger) (at Assets/AkyuiUnity.Xd/Editor/XdImporter.cs:62)
AkyuiUnity.Xd.XdImporter.Import (AkyuiUnity.Xd.XdImportSettings xdSettings, System.String[] xdFilePaths) (at Assets/AkyuiUnity.Xd/Editor/XdImporter.cs:46)
AkyuiUnity.Xd.XdImportSettingsEditor.OnInspectorGUI () (at Assets/AkyuiUnity.Xd/Editor/XdImportSettingsEditor.cs:38)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <b0f293012f4f4a13b3c5a7dc37df7ba8>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by kane9527-e** [comment]
![image](https://user-images.githubusercontent.com/9569527/218304733-c16839a5-82de-42f8-a992-96f71cc1eaf9.png)

**Comment by kane9527-e** [comment]
![image](https://user-images.githubusercontent.com/9569527/218304831-e5b6dc95-dfb0-4eb8-b998-40a8e044f4b6.png)

**Comment by kyubuns** [comment]
There seems to be an error within the vectorgraphics package ( https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html ) in unity.
It seems that one of the objects in the XD file is causing the problem, but I need to get the XD file to reproduce it in order to find out more.

**Comment by kane9527-e** [comment]
[https://drive.google.com/file/d/1eVa3gupP54Vjg3zMtamWbgFvNlKU2ySt/view?usp=share_link](url)
Thank you very much,XD file in url .

**Comment by kyubuns** [comment]
Thank you! You're very helpful!
The reason for the error was that the size of the "直线 2" object in the XD file was zero.
We have fixed it so that objects with size 0 are not parsed, so please update and try it out.
https://github.com/kyubuns/AkyuiUnity/releases/tag/v1.4.1

**Comment by kane9527-e** [comment]
thanks
