### ISSUE TITLE
I didn't get any results

### ISSUE THREAD

**Issue by AltayOlcay** [kyubuns/AkyuiUnity#52]
I am trying to upload the design I created in the Adobe xd project into my Unity project.  I integrated the AkyuiUnity project into my Unity project without any problems. I dragged my project with .xd extension to Drop xd and dropped it. However, I received the reply that your transaction was created without adding anything. I am sharing the screenshot with you. I would be glad if you could help me solve my problem.

![Unity_mFZhlEYk2f](https://github.com/kyubuns/AkyuiUnity/assets/34837149/00b972a8-99b1-4a7d-8ba4-cea628683ce8)

**Comment by kyubuns** [comment]
It is a warning when there is no single Artboard marked for export.
In Adobe XD, press the "Mark for Export" button for the artboard.

![CleanShot_20240420-144110@2x](https://github.com/kyubuns/AkyuiUnity/assets/961165/8e8e4fb6-2ea6-4696-a07a-958b00b1d912)

**Comment by AltayOlcay** [comment]
Thank you very much. I was able to import my project's image aligned and very well.
