### ISSUE TITLE
XD file imported in Unity not creating Prefabs

### ISSUE THREAD

**Issue by raghuaptara** [kyubuns/AkyuiUnity#54]
Hi Team,

I designed and created an sample XD file and followed the rules as mentioned in the document, but if I import the XD file in Unity, it shows below logs in the console, as shown in the below image, and not creating prefabs. Can you please help on this issue?

<img width="518" alt="image" src="https://github.com/user-attachments/assets/a0f24725-8158-4bc1-8a29-8568a446e5a8">

**Comment by kyubuns** [comment]
I think this is probably the same problem.
It’s confusing, isn’t it? I’m thinking of coming up with some measures.
https://github.com/kyubuns/AkyuiUnity/issues/52#issuecomment-2067565943

**Comment by raghuaptara** [comment]
Yes, thank you. It's working after I clicked Mark for Export on the created artboards.

**Comment by kyubuns** [comment]
You’re welcome!
