### ISSUE TITLE
Font files not importing

### ISSUE THREAD

**Issue by raghuaptara** [kyubuns/AkyuiUnity#55]
Hi ,

Text Font files are not importing to Unity project.I would like to know how to import font files also in Unity project when importing XD file

**Comment by kyubuns** [comment]
There is a place in the Asset section of the Xd Import Settings where you can specify the path to the font. Please add the fonts you will use beforehand in this location. They will then be referenced automatically. Note that the font name specified in XD and the font file name must be the same.
https://github.com/kyubuns/AkyuiUnity/blob/main/Manual/Manual_en.md#font-directory-path

**Comment by raghuaptara** [comment]
Ok Thank you.

**Comment by kyubuns** [comment]
you're welcome!
